# Generated by Django 4.2.11 on 2024-04-19 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffuser_passport_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportinfo',
            name='passport_validity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='passport_info',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='staff.passportinfo'),
        ),
    ]
