# Generated by Django 4.2.11 on 2024-04-19 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staffuser_passport_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='passport_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.passportinfo'),
        ),
    ]
