# Generated by Django 4.2.11 on 2024-04-20 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staffuser_passport_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(blank=True, default='', max_length=100)),
                ('company_name', models.CharField(blank=True, default='', max_length=100)),
                ('client_id', models.CharField(blank=True, default='', max_length=100)),
                ('contrct_id', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='staffuser',
            name='hire_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.hireinfo'),
        ),
    ]
