# Generated by Django 4.2.11 on 2024-04-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_hireinfo_staffuser_hire_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hireinfo',
            old_name='contrct_id',
            new_name='contract_id',
        ),
    ]
