# Generated by Django 4.2.11 on 2024-04-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_staffuser_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='test_field',
        ),
    ]
