# Generated by Django 4.2.11 on 2024-04-24 05:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_remove_staffuser_test_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPreferenceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefered_mode', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('date', models.CharField(blank=True, default='', max_length=50)),
                ('time', models.CharField(blank=True, default='', max_length=50)),
                ('time_zone', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looking_for', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('duration', models.CharField(blank=True, default='', max_length=20)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('budget', models.CharField(blank=True, default='', max_length=20)),
                ('currency', models.CharField(blank=True, default='', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='staffuser',
            name='contact_preference_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.contactpreferenceinfo'),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='requirements_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.requirementsinfo'),
        ),
    ]
