# Generated by Django 4.2.11 on 2024-04-26 07:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_email', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=60, null=True)),
                ('company_location', models.CharField(blank=True, max_length=255, null=True)),
                ('company_url', models.CharField(blank=True, max_length=255, null=True)),
                ('company_register_no', models.CharField(blank=True, max_length=20, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('terms', models.BooleanField(default=False)),
                ('plan_selected', models.IntegerField(default=0)),
                ('plan_expiry', models.DateField(null=True)),
                ('interested_in', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('looking_for', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('duration', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('agree_terms', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_company', models.CharField(blank=True, max_length=60, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('company_pan', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_name', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_email', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_name', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_email', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
